#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("RGBFilters.Resource", IsApplication=true)]

namespace RGBFilters
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_cancel = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_cancel_pressed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_done = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_done_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int cat = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int crop_circle = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon_2_3 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int icon_3_4 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int icon_3_5 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int icon_crop = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int icon_custom = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int icon_original = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int icon_square = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int image_for_cropping = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int monoandroidsplash = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int alphaSeek = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int blueSeek = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int greenSeek = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int info = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int redSeek = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int surfaceView1 = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int monoandroidsplash = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
